name: Docker_Win_Test

on:
  push:
    branches:
      — '*'
    tags:
      — '*'
    pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          # build-args: |
          #   URL=${{ secrets.BASE_URL }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker_test:1.0.0
